MARP-620 Add release-drafter workflow
axonivy-market/deepl-connector pull request #41
Opened 2024-08-19 07:59 UTC by ndkhanh-axonivy

This PR adds the Release Drafter workflow to the repository.

2024-08-19 11:06 UTC, ivy-rew approved these changes

2024-08-21 02:48 UTC, nqhoan-axonivy requested changes
Hold on, please don't merge this PR:
the master file https://github.com/axonivy-market/github-workflows/blob/v4/.github/workflows/release-drafter.yml has no event workflow-call.
So @ndkhanh-axonivy please create a PR to adapt it, then maybe you must change this script to v5 or higher

2024-08-21 06:32 UTC, ivy-rew commented
> Hold on, please don't merge this PR: the master file https://github.com/axonivy-market/github-workflows/blob/v4/.github/workflows/release-drafter.yml has no event workflow-call. So @ndkhanh-axonivy please create a PR to adapt it, then maybe you must change this script to v5 or higher

I think we could also re-use the tag v4  (as we do not introduce any changes for the existing pipelines)
Simply delete the v4 remote tag in github-workflows and re-create it from a commit that contains the release-drafter should be sufficient.

2024-08-26 07:03 UTC, ivy-rew approved these changes

2024-08-26 09:33 UTC, merged